"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-05-18

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_seeded', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_users_username'), ['username'], unique=True)

    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countries_code'), ['code'], unique=True)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employment_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('is_active_status', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)

    op.create_table('job_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'name', name='uq_jobtitle_dept_name')
    )
    with op.batch_alter_table('job_titles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_titles_department_id'), ['department_id'], unique=False)

    op.create_table('oauth_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_lifetime_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_clients_client_id'), ['client_id'], unique=True)

    op.create_table('states_provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'name', name='uq_states_country_name')
    )
    with op.batch_alter_table('states_provinces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_states_provinces_country_id'), ['country_id'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('address_line_1', sa.String(length=200), nullable=True),
    sa.Column('address_line_2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('state_province_id', sa.Integer(), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('home_phone', sa.String(length=50), nullable=True),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('work_email', sa.String(length=255), nullable=True),
    sa.Column('cost_center', sa.String(length=100), nullable=True),
    sa.Column('employment_status_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('job_title_id', sa.Integer(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('supervisor_id IS NULL OR supervisor_id != id', name='ck_employee_no_self_supervision'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['employment_status_id'], ['employment_statuses.id'], ),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_titles.id'], ),
    sa.ForeignKeyConstraint(['state_province_id'], ['states_provinces.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_country_id'), ['country_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_employee_number'), ['employee_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_employment_status_id'), ['employment_status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index('ix_employees_lastname_firstname', ['last_name', 'first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_supervisor_id'), ['supervisor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_supervisor_id'))
        batch_op.drop_index('ix_employees_lastname_firstname')
        batch_op.drop_index(batch_op.f('ix_employees_is_archived'))
        batch_op.drop_index(batch_op.f('ix_employees_employment_status_id'))
        batch_op.drop_index(batch_op.f('ix_employees_employee_number'))
        batch_op.drop_index(batch_op.f('ix_employees_country_id'))

    op.drop_table('employees')
    with op.batch_alter_table('states_provinces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_states_provinces_country_id'))

    op.drop_table('states_provinces')
    with op.batch_alter_table('oauth_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_clients_client_id'))

    op.drop_table('oauth_clients')
    with op.batch_alter_table('job_titles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_titles_department_id'))

    op.drop_table('job_titles')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    op.drop_table('employment_statuses')
    op.drop_table('departments')
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_code'))

    op.drop_table('countries')
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_users_username'))

    op.drop_table('app_users')
    # ### end Alembic commands ###
